### ISSUE TITLE
Angular v5 migration

### ISSUE THREAD

**Issue by dherges** [dherges/ng-packagr#269]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Migrate and support Angular v5

Current Status: `v2.0.0-rc.5`

#### Expected Behaviour

This issue keeps track of the migration effort to Angular version 5. The discussion is therefore locked and individual issues are referenced from here:

#### Tasks

- [x] Update typescript to ~2.4.2 (#270)
- [x] Switch to `@angular/compiler-cli` for v5 support (#261, #219)
- [x] Check whether lettable rxjs operators work (#247, #307)
- [x] Improve test coverage of JavaScript "binaries"
- [x] `StaticInjectorError` (#335. #299, #302, #304)
- [x] Triple-slash references must not cause regression (#443)

#### Angular Issues that will help

- [ ] angular/angular#20906
- [ ] angular/angular#21339

#### Other Issues

- User questions on Angular 5 in general (#246)
- Metadata version 4 (#258)
- Clarity NG 5 Updates (vmware/clarity#1659)

#### Version Information

```
ng-packagr: v1.6.x
```

**Comment by dherges** [comment]
#443 is at the moment last blocking issue for 2.0.0
